[package]
name = "live-whirl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
coolor = "*"
bevy = "0.11.3"
bevy_rapier2d = { version = "0.22.0", features = ["simd-stable", "parallel", "debug-render-2d"] }
# bevy_rapier2d = { version = "0.22.0", features = ["simd-stable", "debug-render-2d"] }